### ISSUE TITLE
Troubles getting examples to work properly

### ISSUE THREAD

**Issue by jrmazarura** [jhlau/topic_interpretability#2]
I am a beginner and need a bit of help. I am simply trying to run run-oc.sh and run-wi.sh codes on the examples that come with the code. 

For windows, where is the correct place to insert 

            if __name__ == '__main__':

in ComputeWordCount.py?

I need to do this in order to solve this error:

            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.

Lastly, when I now want to run the codes for my own topic evaluation, can I use the orginal data as my reference corpus or must I download another one? (I am a little bit confused about why the reference corpus in wiki is in two files as opposed to just one.)

**Comment by jhlau** [comment]
Unfortunately I do not provide support for Windows, and do not know if the code would actually run on it.

The reference corpus on GitHub is a toy data serving just as an example. You'll need to download the Wikipedia dump and preprocess it in order to use it as reference corpus.
