### ISSUE TITLE
How to automatically create topic intruders?

### ISSUE THREAD

**Issue by bwang482** [jhlau/topic_interpretability#3]
Thanks for the great work Jey Han! It has really helped my work I have to say! 

I have noticed in this implementation that the topic intruder word is required as a input. Can you please point to me where the process of generating topic intruders can be automated as is mentioned in your papers?

Thanks!

**Comment by jhlau** [comment]
Hi, we did not provide code for generating intruder words as it is dependent on the topic model implementation (how the distribution over words for topics is stored, etc).

In terms of the procedure for choosing intruder words, it's described in the paper:

> In the word intrusion task, each topic is presented as a list of sixwords—the five most probable topic words and a randomly-selected “intruder word”, which has low probability in the topic of interest, but high probability in other topics

**Comment by bluemonk482** [comment]
Thanks Jey Han. I have come across this paper today: http://www.dcs.gla.ac.uk/~anjie/papers/fang2016ecir.pdf

that uses Twitter dataset for reference corpus for computing PMI. Can I use switch the wiki ref data with my Twitter corpus (one tweet for each new line) for computing word occurrence with your code? Or is there any caveat in e.g. ComputeWordCount.py that I should modify for tweets? Thanks again!
