### ISSUE TITLE
Computing word occurrence (thus run-oc) with Twitter ref corpus?

### ISSUE THREAD

**Issue by bwang482** [jhlau/topic_interpretability#4]
Thanks for answering my previous question Jey Han. I have come across this paper today: http://www.dcs.gla.ac.uk/~anjie/papers/fang2016ecir.pdf

that uses Twitter dataset for reference corpus for computing PMI. Can I use switch the wiki ref data with my Twitter corpus (one tweet for each new line) for computing word occurrence with your code? Or is there any caveat in e.g. ComputeWordCount.py that I should modify for tweets? Thanks again!

**Comment by jhlau** [comment]
You can of course switch the wiki ref data with your Twitter corpus. As long as you keep the format consistent that should be fine. The important part would be the preprocessing of the Twitter corpus - make sure it's tokenised properly (you might want to use a Twitter word tokeniser) and you might also want to deal with hashtags differently.
