### ISSUE TITLE
Full reference corpus?

### ISSUE THREAD

**Issue by kkrasnas** [jhlau/topic_interpretability#5]
Hello,
I have a question regarding the reference corpus. It says wiki, however the files are very small for wikipedia dump. I am trying to reproduce your tests on TDLM, could you please tell me if this is the reference corpus you used for the experiments? I doubt it, since this corpus is lemmatized, but it would be good to confirm. If you can direct me in the path of the reference corpus you used for TDLM. 
Thank you!

**Comment by jhlau** [comment]
The reference corpus on github is only meant to be used as an example for running the script. We don't provide the reference corpus as it is very large, so you should download the wikipedia dumps yourself and preprocess them.
