### ISSUE TITLE
Calculation of NPMI when combined_count=0

### ISSUE THREAD

**Issue by UmeanNever** [jhlau/topic_interpretability#6]
Hi, 

I'm using this code to calculate NPMI in my experiments these days. During which I find some strange results so I carefully read the code and it seems that the calculation of NPMI when combined_count=0 is a little different from my understanding.

In _ComputeObservedCoherence.py_,
The NPMI is calculated by:
```
     if (args.metric == "pmi") or (args.metric == "npmi"):
        if w1_count == 0 or w2_count == 0 or combined_count == 0:
            result = 0.0
        else:
            result = math.log((float(combined_count)*float(window_total))/ \
                float(w1_count*w2_count), 10)
            if args.metric == "npmi":
                result = result / (-1.0*math.log(float(combined_count)/(window_total),10))
```
When combined_count (which is the co-occurence of two words) is 0, the result is set to **0**.

But for me, the NPMI is allowed to be negative and when the two words never occur in the same window, the NPMI result here should be **-1**. (From the definition of NPMI, when p(w_i, w_j) -> 0, by L'Hopital's Rule, we get the NPMI=-1.)

So should it be that when combined_count=0 and w1_count!=0, w2_count!=0, the NPMI result for this pair is -1?

**Comment by jhlau** [comment]
It's probably just a matter of definition, since there's no log value that you can calculate when you have no observed combined counts. Feel free to set it to -1 and see if it does better empirically (or probably it will have very little impact as there won't be many of such cases).

**Comment by UmeanNever** [comment]
Set it to -1 does make some impact when used in specific domain where no oberserved combined counts appears more often. I agree that this should be by one's own choice. Thanks for the explanation.
