### ISSUE TITLE
preprocessing step needed

### ISSUE THREAD

**Issue by un-lock-me** [jhlau/topic_interpretability#7]
Hi,

Thanks for sharing your code. I see that you have included a toy example of wiki here. I think we need to download wiki dump in our side and then preprocess it. 
Do you mind explaining which preprocessing step I need to take?

Thanks~
Saria

**Comment by jhlau** [comment]
If I remember correctly, we use WikiExtractor (https://github.com/attardi/wikiextractor) to clean the wiki dump, and used Stanford Parser to tokenise words and sentences.

**Comment by un-lock-me** [comment]
I changed the question, my previous question does not make sense as we have to use external source for coherence measurement:|

Just one more question here, in the papers that report about the coherence they got for their model they never discuss which external source they use for evaluation. Do you have any idea of this?
I think based on the external source the score might change a lottt. I greatly appreciate if you could share your idea a regarding this with me.

Thanks~
